// task-tracker-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { TaskInputComponent } from './components/task-input/task-input.component';
import { TaskListComponent } from './components/task-list/task-list.component';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Task } from './models/task.model';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, FormsModule, TaskInputComponent, TaskListComponent],
  templateUrl: './app.component.html',
})
export class AppComponent {
  tasks: Task[] = [];

  addTask(title: string) {
    const newTask: Task = {
      id: Date.now(),
      title,
      completed: false,
    };
    this.tasks.push(newTask);
  }

  toggleComplete(id: number) {
    const task = this.tasks.find((t) => t.id === id);
    if (task) task.completed = !task.completed;
  }

  deleteTask(id: number) {
    this.tasks = this.tasks.filter((t) => t.id !== id);
  }
}

<div class="app-container">
  <img 
  src="https://angular.io/assets/images/logos/angular/angular.svg" 
  alt="Angular Logo"
  class="logo"
  width="64"
  height="64"
/>
  <h1>Task Tracker</h1>
  <app-task-input (taskAdded)="addTask($event)"></app-task-input>
  <app-task-list 
    [tasks]="tasks"
    (complete)="toggleComplete($event)"
    (delete)="deleteTask($event)">
  </app-task-list>
</div>

// task-tracker-react/src/App.tsx
import { useState } from 'react';
import type { Task } from './types';
import TaskInput from './components/TaskInput';
import './index.css';

function App() {
  const [tasks, setTasks] = useState<Task[]>([]);

  const addTask = (title: string) => {
    const newTask: Task = { id: Date.now(), title, completed: false };
    setTasks(prev => [...prev, newTask]);
  };

  const toggleComplete = (id: number) => {
    setTasks(prev =>
      prev.map(task =>
        task.id === id ? { ...task, completed: !task.completed } : task
      )
    );
  };

  const deleteTask = (id: number) => {
    setTasks(prev => prev.filter(task => task.id !== id));
  };

  return (
    <div className="app-container">
          <img
      src="https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg"
      alt="React Logo"
      className="logo"
      width="64"
      height="64"
    />
      <h1>Task Tracker</h1>
      <TaskInput onAdd={addTask} />
      <ul>
        {tasks.map(task => (
          <li key={task.id}>
            <span
              className={`task-text ${task.completed ? 'completed' : ''}`}
              onClick={() => toggleComplete(task.id)}
            >
              {task.title}
            </span>
            <div className="task-buttons">
              <button onClick={() => toggleComplete(task.id)}>✓</button>
              <button onClick={() => deleteTask(task.id)}>🗑️</button>
            </div>
          </li>
        ))}
      </ul>
    </div>
  );
}

export default App;
